### ISSUE TITLE
Undeliverable Exception when 

### ISSUE THREAD

**Issue by TimoPtr** [Polidea/RxAndroidBle#410] opened 2018-04-09 15:24 UTC
### Summary
Our object disconnect from the phone after we send a message and next we shutdown the BLE adapter (with UiAutomator). But we received an Undelivrable exception after the disconnection some times.
  
### Library version
`1.6.0-SNAPSHOT`

#### Preconditions
Stop the BLE Adapter just after send a message. 

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`
04-09 13:21:28.546 debug BLEObject disconnect BLE
04-09 13:21:28.546 debug BluetoothGatt setCharacteristicNotification() - uuid: XXXXXXXXXXXX enable: false
04-09 13:21:28.556 debug RxBle#ConnectionOperationQueue QUEUED   DescriptorWriteOperation(129367962)
04-09 13:21:28.556 debug RxBle#ConnectionOperationQueue STARTED  DescriptorWriteOperation(129367962)
04-09 13:21:28.556 error Home ERROR UNHANDLED ! 
04-09 13:21:28.556 error Home io.reactivex.exceptions.UndeliverableException: java.util.ConcurrentModificationException
04-09 13:21:28.556 error Home 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:52)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:122)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:514)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:311)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:594)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:520)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:311)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:594)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:520)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:311)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:86)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.dispose(ObservableDoFinally.java:99)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.dispose(ObservableSubscribeOn.java:73)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.operators.observable.ObservableUnsubscribeOn$UnsubscribeObserver$DisposeTask.run(ObservableUnsubscribeOn.java:95)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
04-09 13:21:28.556 error Home 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-09 13:21:28.556 error Home 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-09 13:21:28.556 error Home 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-09 13:21:28.556 error Home 	at java.lang.Thread.run(Thread.java:818)
04-09 13:21:28.556 error Home Caused by: java.util.ConcurrentModificationException
04-09 13:21:28.556 error Home 	at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
04-09 13:21:28.556 error Home 	at java.util.LinkedList.removeOneOccurrence(LinkedList.java:835)
04-09 13:21:28.556 error Home 	at java.util.LinkedList.removeFirstOccurrenceImpl(LinkedList.java:830)
04-09 13:21:28.556 error Home 	at java.util.LinkedList.remove(LinkedList.java:665)
04-09 13:21:28.556 error Home 	at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$7.cancel(DisconnectionRouter.java:153)
04-09 13:21:28.556 error Home 	at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
04-09 13:21:28.556 error Home 	... 23 more
04-09 13:21:28.566 debug RxBle#ClientOperationQueue QUEUED   DisconnectOperation(125497547)
04-09 13:21:28.566 info RxBle#ConnectionOperationQueue Connection operations queue to be terminated (XXXXXXXXXXXX)
04-09 13:21:28.566 debug RxBle#ClientOperationQueue STARTED  DisconnectOperation(125497547)
04-09 13:21:28.566 debug BluetoothManager getConnectionState()
04-09 13:21:28.566 debug BluetoothManager getConnectedDevices
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue Queue's awaitRelease() has been interrupted abruptly while it wasn't released by the release() method.
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue java.lang.InterruptedException
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.lang.Object.wait(Native Method)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at com.polidea.rxandroidble2.internal.serialization.QueueSemaphore.awaitRelease(QueueSemaphore.java:15)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at com.polidea.rxandroidble2.internal.serialization.ConnectionOperationQueueImpl$1.run(ConnectionOperationQueueImpl.java:71)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-09 13:21:28.566 warn RxBle#ConnectionOperationQueue 	at java.lang.Thread.run(Thread.java:818)
04-09 13:21:28.576 debug BluetoothGatt cancelOpen() - device: XXXXXXXXXXXX
04-09 13:21:28.576 debug BluetoothGatt onClientConnectionState() - status=0 clientIf=10 device=XXXXXXXXXXXX
04-09 13:21:28.586 debug RxBle#BluetoothGatt onConnectionStateChange newState=0 status=0
04-09 13:21:28.586 debug BluetoothGatt close()
04-09 13:21:28.586 debug RxBle#ConnectionOperationQueue FINISHED DescriptorWriteOperation(129367962) in 30 ms
04-09 13:21:28.586 debug RxBle#Executors$RunnableAdapter Terminated.
04-09 13:21:28.586 debug BluetoothGatt unregisterApp() - mClientIf=10
04-09 13:21:28.596 debug RxBle#ClientOperationQueue FINISHED DisconnectOperation(125497547) in 31 ms
04-09 13:21:35.566 debug testAlreadyCreatedAccountWithOnGoingRecord Starting UI Test
04-09 13:21:35.566 debug BluetoothAdapter disable()
04-09 13:21:36.026 debug BluetoothAdapter ondisableBLE
04-09 13:21:36.026 debug BluetoothAdapter There are no active google scan apps, stop scan
04-09 13:21:36.026 debug BluetoothLeScanner stopAllScan standalone boolean is value is = false
04-09 13:21:36.026 debug BluetoothLeScanner Exiting stopAllScan
04-09 13:21:36.096 debug BluetoothAdapter onBluetoothStateChange: up=false
04-09 13:21:36.096 debug BluetoothAdapter Bluetooth is turned off, stop adv
04-09 13:21:36.096 debug BluetoothAdapter There are no active google scan apps, stop scan
04-09 13:21:36.096 debug BluetoothLeScanner stopAllScan standalone boolean is value is = false
04-09 13:21:36.096 debug BluetoothLeScanner Exiting stopAllScan

#### Actual result
Disconnect from the device produce undelivrable exception

#### Expected result
Disconnect from the device without undelivrable exception

**Comment by dariuszseweryn** [comment] 2018-04-09 15:36
Looks like a duplicate of #383 
Reopen if you think otherwise

**Closed by dariuszseweryn** 2018-04-09 15:36 UTC
Labels: duplicate
