### ISSUE TITLE
Internal error when setting up notification.

### ISSUE THREAD

**Issue by marcbaldwin** [Polidea/RxAndroidBle#155] opened 2017-03-31 14:17 UTC
### Summary
`BleCannotSetCharacteristicNotificationException` when setting up notification on characteristic.

#### Steps to reproduce actual result
1. Connect to BLE device
2. Discover services
3. Get characteristic
4. Setup notification for characteristic

```
device.establishConnection(context, true)
      .flatMap(connection -> connection.discoverServices()
            .flatMap(services -> Observable.zip(
                                services.getCharacteristic(UART_UUID, TX_UUID),
                                services.getCharacteristic(UART_UUID, RX_UUID),
                                (tx, rx) -> {
                                     ...
                                     connection.setupNotification(rx)
                                     ...
                                }
                        )
            )
      )
```

#### Actual result
Exception: BleCannotSetCharacteristicNotificationException

#### Expected result
Characteristic notification observable to be set up.

The exception is caused as `BluetoothGatt.setCharacteristicNotification` returns false, due to the fact `mClientIf` has not been initialised. `mClientIf` is initialised in the `onClientRegistered` callback.

If I reconnect to the device then the notification setup succeeds.

Any help with this would be greatly appreciated.

Thanks,

 Marc

**Comment by dariuszseweryn** [comment] 2017-03-31 14:27
Hello @marcbaldwin 
Could you add what phone / OS you use?
Additionally please set `RxBleLog.setLogLevel(RxBleLog.VERBOSE)` and paste the logs from the application.

**Comment by dariuszseweryn** [comment] 2017-04-10 09:36
Since there is no contact and so far the described situation is working as designed (`onError()` invoked when the notification cannot be set) – I am closing.

**Closed by dariuszseweryn** 2017-04-10 09:36 UTC
