### ISSUE TITLE
BleDisconnectedException when connect to deivce sometimes

### ISSUE THREAD

**Issue by liunewshine** [Polidea/RxAndroidBle#156] opened 2017-04-01 14:30 UTC
### Summary
Continuing establishConnection then unsubscribe，sometimes connect success，sometimes thow BleDisconnectedException
#### Steps to reproduce actual result
Continuing establishConnection then unsubscribe
#### Actual result
sometimes connect success，sometimes thow BleDisconnectedException
#### Expected result
always connect success
![qq 20170401222826](https://cloud.githubusercontent.com/assets/7698511/24579569/91266c52-172a-11e7-9e5c-54539ad0d60e.png)
![qq 20170401223000](https://cloud.githubusercontent.com/assets/7698511/24579581/c30fa80a-172a-11e7-8a5a-4f17d46978b7.png)

**Comment by dariuszseweryn** [comment] 2017-04-03 16:39
Hello @liunewshine
 Excuse me if I did not understand you correctly. Do you have issue that `RxBleDevice.establishConnection()` does sometimes emit a `BleDisconnectedException`?

**Comment by dariuszseweryn** [comment] 2017-04-10 09:37
Since there is no contact and the described situation is working as designed (`onError()` invoked when the connection cannot be established) – I am closing.

**Closed by dariuszseweryn** 2017-04-10 09:37 UTC
