### ISSUE TITLE
Rx3 support

### ISSUE THREAD

**Issue by Ditscheridou** [Polidea/RxAndroidBle#714] opened 2020-08-17 13:45 UTC
Hi guys, 

im currently using the rxble library in my project, but i will be forced to use rx3 in a few month. It would be awesome when you can support rxjava3 for this library.

**Comment by RobLewis** [comment] 2020-08-17 20:40
Duplicate of #690

**Comment by dariuszseweryn** [comment] 2020-08-20 18:17
☝️

**Closed by dariuszseweryn** 2020-08-20 18:17 UTC
Labels: enhancement, idea
