### ISSUE TITLE
Perspectives for Rxjava 2.0 support

### ISSUE THREAD

**Issue by recoverrelax** [Polidea/RxAndroidBle#228] opened 2017-06-21 13:46 UTC
With Rxjava 2.0 a couple months ago, and Rxjava 1.0 deprecation, i would ask if you can (maybe), make a version for Rxjava 2.0 of this library. Soon, users will think twice about using this library, as Rxjava 1.0 as dependency is mandatory. I know making it compatible with 1.0 and 2.0 is a tone of works, but porting it to 2.0 is relatively simple. Is this in your mind soon?

**Comment by dariuszseweryn** [comment] 2017-06-21 13:58
We have it in plans.
Duplicate of #72 
Closing

**Closed by dariuszseweryn** 2017-06-21 13:58 UTC
