### ISSUE TITLE
Lower speed on multiple writes

### ISSUE THREAD

**Issue by rgarciaotc** [Polidea/RxAndroidBle#296] opened 2017-10-24 06:59 UTC
I want to do multiple writes using a timer.
I am trying to do the following:

When I do a write I want to recieve the response (OnWriteSuccess) and when I get it, I will write again.

The first ten - twenty writes are ok but after that, I have a delay between each write of 2 - 4 seconds.

**Comment by dariuszseweryn** [comment] 2017-10-24 10:23
I see that you have already posted a question on [stackoverflow](https://stackoverflow.com/questions/46904360/lower-speed-on-multiple-writes)—answering there.

As it is put in the disclaimer—this question is not a bug nor a feature request but a question about usage and this is not a good place for answer. Closing.

**Closed by dariuszseweryn** 2017-10-24 10:23 UTC
