### ISSUE TITLE
Possible issue with using ReplayingShare to share connections

### ISSUE THREAD

**Issue by streetsofboston** [Polidea/RxAndroidBle#406] opened 2018-03-29 20:59 UTC
This is more of a question or discussion, not an issue, since it doesn't relate to any of the RxAndroidBle code. However, it does relate to the recommendation to use `ReplayingShare` instead of the `ConnectionShareAdapter`.

This is the issue.
- A device was just scanned.
- The device is recognized and grabbed. 
- Then `establishConnection` is called on this device and shared through the use of `ReplayingShare`. The resulting shared Rx observable is cached in the code that grabbed the device.
- Say an observer subscribes to the above shared Rx observable and then flat-maps with a `connection.readCharacteristic`. All goes well, data is read hand handled.
- Then there is an issue with the Bluetooth adapter or reception, but it is quickly resolved. However, the current connection is no longer valid. It is stale, the device is disconnected. The current observer receives an onError and handles the disconnection error.
- A little later a second observer subscribes to the above shared Rx observable.
- Since this shared Rx observable uses the `ReplayingShare`, the second subscription causes an invalid/stale connection to be emitted by the `ReplayingShare`. 

The problem is that `ReplayingShare` does not react to finalizations (onComplete, onError or onDispose). This means that `ReplayingShare` cannot be used to share resources that become invalid/stale as soon as subscriptions to these resources are finalized. The `RxBleConnection` is such a resource. 

In our project, I worked around this by copying the `ReplayingShare` code and add a little bit of code:
In the two `apply` methods of the `ReplayingShare`, I changed this
- `upstream.doOnNext(lastSeen).share()` 
to this
- ` upstream.doFinally { lastSeen.value = null }.doOnNext(lastSeen).share()`

This prevents invalid/state `RxBleConnection`s to be emitted and solved the issues we had with concurrent connections.

**Comment by RobLewis** [comment] 2018-03-29 22:41
Has anyone reported this to Jake? 
Question: It's my understanding that in RxJava2, sources aren't permitted to emit `null`. Does your solution violate this?

**Comment by RobLewis** [comment] 2018-03-29 22:47
Half-baked idea: might it be possible to use the `.retryWhen()` operator to handle this situation?

**Comment by streetsofboston** [comment] 2018-03-29 22:47
I have not reported this to Jake, since I think it is not an issue for the `ReplayingShare` itself. 

My issue is that caution needs to be taken with the *recommendation* of using ReplayingShare for sharing RxBleConnections. 

When the `lastSeen.value` is `null`, a `null` item is not emitted; instead nothing is emitted (if you look at `ReplayingShare`'s java-code, you see that `onNext` is not called when `value == null`). No Rx violation :)

**Comment by streetsofboston** [comment] 2018-03-29 22:54
@RobLewis In answer to your second question.
`retryWhen` would work only for the first observer and possibly fix it disconnection issue. 

If you put the `retryWhen` before the composition with the ReplayingShare, you'll always retry for all subscribers.... and sometime you don't want to. 

At some point, retries should be given up and you'll want to just let it fail. In this case, you'd have an invalid/stale RxBleConnection cached in the `ReplayingShare`. The next observer who then subscribes to this shared connection Rx chain may then receive that stale connection, while it should instead just cause a re-subscription of the observable returned by `establishConnection` without a preceding replay from `ReplayingShare`.

If the RxBleConnection had a method like `isConnected` or `isValid` or something, one could use a filter or some other Rx chain of commands to ignore them and get a fresh RxBleConnection instead.

**Comment by RobLewis** [comment] 2018-03-30 00:00
I don't have time to work through it now (I'm still learning), but I think `.retryWhen()` might be able to handle this correctly. Took me quite a while just to figure out what it does, but it seems quite powerful.

**Comment by RobLewis** [comment] 2018-04-07 18:51
@streetsofboston Embarrassed to ask, but is there a giant looming hole in my understanding of Java? I'm referring to your code snippet `upstream.doFinally { lastSeen.value = null }.doOnNext(lastSeen).share()`. The docs say that `.doFinally()` takes an `Action` parameter, where an "Action" is apparently any code that takes no parameters and returns no result. Is it actually permissible to just plop a chunk of code inside braces in place of the method call argument and its enclosing parentheses? Please explain.

**Comment by streetsofboston** [comment] 2018-04-07 19:16
@RobLewis The code snippet I posted in in Kotlin, not Java. 

In this case the Java `Action` is an interface with only one method, a so-called SAM (Single Abstract Method). Kotlin' Java interoperability allow lambdas to be assigned to SAMs, where Kotlin compiler does the necessary translation from lambda to `Action` instance.

In my example, the Java `Action` is assigned a Kotlin lambda `{ lastSeen.value = null }`

**Comment by RobLewis** [comment] 2018-04-07 19:57
@streetsofboston D'oh! Thanks. (I've actually started learning Kotlin, but obviously haven't gotten that far yet.) 
Should we delete this little sub-thread?

**Comment by RobLewis** [comment] 2018-04-09 21:56
@streetsofboston Right, `doFinally()` covers those cases, too.

**Comment by RobLewis** [comment] 2018-05-18 16:18
I touched base with Wharton recently and he said that he should soon have time to work on this.

**Comment by RobLewis** [comment] 2018-07-04 23:54
OK, someone remind me why this isn't a good way to share a connection: 

```
Observable<RxBleConnection> sharedConnectionObservable = device.establishConnection( false )
    .replay(1).refCount(); 
```
and to use it: 

```
Disposable disp1 = sharedConnectionObservable.subscribe( ... ); 
Disposable disp2 = sharedConnectionObservable.subscribe( ... );
``` 

etc. 

`replay(1)` buffers the (sole) connection from upstream and re-emits it to new subscribers. `refCount()` kicks things off by connecting to the upstream, then maintains the connection as long as there is at least one subscriber. Presumably if `establishConnection()` signals an error (as when the connection is lost), it will be forwarded to all subscribers. And when the last subscriber disposes, the connection is ended. 

What am I missing?

**Comment by dariuszseweryn** [comment] 2018-07-05 16:08
Probably that if you have:
```
Observable<RxBleConnection> sharedConnectionObservable = device.establishConnection( false )
    .replay(1).refCount(); 
```
and do:
```
Disposable disp1 = sharedConnectionObservable.subscribe( ... ); 
// wait until connection is established
Disposable disp2 = sharedConnectionObservable.subscribe( ... );
```
Then the second `.subscribe()` will never get the emitted `RxBleConnection` as it happened _before_ the second subscription to `.refCount()`.

`.refCount()` makes only a single subscription to the upstream therefore `.replay()` will get subscribed only once

**Comment by RobLewis** [comment] 2018-07-06 14:40
@dariuszseweryn OK, I _think_ I understand that, thanks. What about using the `.cache()` operator? Alternatively, use `.replay(1)` without `.refCount()` and make an explicit call to `.connect()` to get things started? (It's my understanding that a single `.connect()` invocation works for current and future subscribers.) If the last subscriber to `.replay()` disposes will the BLE connection be released? 
I don't mean to beat this to death but it seems like there must be some way of handling this common situation straightforwardly.

**Comment by dariuszseweryn** [comment] 2018-07-09 09:07
Doesn't matter if you use `.cache()` or `.replay()` before `.refCount()` — it will behave almost the same.

`.replay()` without `.refCount()` and explicitly `.connect()` should do the trick but you're getting back to manually managing the connection.

> If the last subscriber to .replay() disposes will the BLE connection be released?

Afaik — no. To release (close) the connection one should dispose the result of `connectionObservable.connect()`

> I don't mean to beat this to death but it seems like there must be some way of handling this common situation straightforwardly.

I would like to know how to handle such situation easily and bake it into the library so others would not need to tackle it on their own but since there is room for a `ReplayingShare` I do not think there is

**Comment by BernhardReu** [comment] 2018-07-16 07:02
We are using this library in one of our company projects and it is working great so far. Thank you for all your effort!

I was also poring a lot over connection sharing. I think the great challenge with a shared connection observable are the error scenarios. After thinking through a lot of possible solutions (some with vanilla RxJava, some with helpers like ReplayingShare) I have recently started to validate them.

First I was thinking about the mentioned drawback of simply using `.replay(1).refCount()`. I just could not believe that the second (late) observer would not get the replayed connection..

That's why I wrote the following little unit test which should reproduce this behavior (without actually including your library) - and it passes!

```
// Given
Object connection = new Object();
PublishSubject<Object> connectionSubject = PublishSubject.create();
Observable<Object> sharedConnection = connectionSubject.replay(1).refCount();

// When
TestObserver<Object> observer1 = sharedConnection.test();
connectionSubject.onNext(connection);
TestObserver<Object> observer2 = sharedConnection.test();

// Then
observer1.assertValueCount(1);
observer2.assertValueCount(1);
```

Did I miss something?

While I haven't figured out my ideal path for connection sharing (yet) I just wanted to share this information.

**Comment by BernhardReu** [comment] 2018-07-16 13:49
@streetsofboston I know that this does not handle stale connections. I just wanted to clarify the behavior of `replay(1).refCount()` . It was not meant to be a solution covering all cases.
If the previous discussion was meant to also cover the error case then I misread the answer from @dariuszseweryn and I am sorry.
Anyway, I am currently experimenting with a solution similar to the `ConnectionShareAdapter` and the `ReplayingShare` using a Transformer and some internal (thread safe) state to handle the case of stale connections. I will definitely let you know if I make useful progress.

**Comment by streetsofboston** [comment] 2018-07-16 14:03
@BernhardReu In our projects we tried such a solution and it is working for us quite well with the Ble-Connections. Here is the solution's gist:
https://gist.github.com/streetsofboston/cf14543f0467af5cf990ac91b62b4606

**Comment by dariuszseweryn** [comment] 2018-09-26 09:14
It looks like the `ReplayingShare` in version `2.1.0` and above should do the trick now. I am closing this thread — hopefully everyone can workout their way with either `ReaplayingShare` or with `replay(1).refCount()` or however else they like. :)

**Closed by dariuszseweryn** 2018-09-26 09:14 UTC
Labels: awaiting feedback
