### ISSUE TITLE
BluetoothGatt can't close when device is try to connect.

### ISSUE THREAD

**Issue by kexuejin** [Polidea/RxAndroidBle#56] opened 2016-08-16 23:14 UTC
### Summary
<br />Normal if device is connected,when exit activity or fragment,the bluetooth will close,but if the device is try to connect(the device is offline),the bluetooth not close right now,after maybe one or two minute later,the bluetooth close.
```
08-17 07:31:56.260 7477-7477/com.polidea.rxandroidble.sample D/RxBle#Radio:   QUEUED RxBleRadioOperationConnect(140952845)
08-17 07:31:56.262 7477-7498/com.polidea.rxandroidble.sample D/RxBle#Radio:  STARTED RxBleRadioOperationConnect(140952845)
08-17 07:31:56.279 7477-7477/com.polidea.rxandroidble.sample V/RxBle#BleConnectionCompat: Connecting without reflection
08-17 07:31:56.281 7477-7477/com.polidea.rxandroidble.sample D/BluetoothGatt: connect() - device: C6:45:40:E8:BC:3F, auto: false
08-17 07:31:56.281 7477-7477/com.polidea.rxandroidble.sample D/BluetoothGatt: registerApp()
08-17 07:31:56.285 7477-7477/com.polidea.rxandroidble.sample D/BluetoothGatt: registerApp() - UUID=f0583ad9-c73c-4ed6-8324-e6e3ec359e83
08-17 07:31:56.287 7477-7489/com.polidea.rxandroidble.sample D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
08-17 07:32:00.024 7477-7477/com.polidea.rxandroidble.sample D/RxBle#Radio:   QUEUED RxBleRadioOperationDisconnect(266187038)
08-17 07:32:00.203 7477-7504/com.polidea.rxandroidble.sample E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9c4fa050
08-17 07:32:00.354 7477-7477/com.polidea.rxandroidble.sample E/Sample: onDestory

08-17 07:32:26.335 7477-7488/com.polidea.rxandroidble.sample D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=5 device=C6:45:40:E8:BC:3F
08-17 07:32:26.337 7477-7488/com.polidea.rxandroidble.sample D/RxBle#BluetoothGatt: onConnectionStateChange newState=0 status=133
08-17 07:32:26.358 7477-7498/com.polidea.rxandroidble.sample D/RxBle#Radio: FINISHED RxBleRadioOperationConnect(140952845)
08-17 07:32:26.359 7477-7498/com.polidea.rxandroidble.sample D/RxBle#Radio:  STARTED RxBleRadioOperationDisconnect(266187038)
08-17 07:32:26.363 7477-7477/com.polidea.rxandroidble.sample D/BluetoothManager: getConnectionState()
08-17 07:32:26.363 7477-7477/com.polidea.rxandroidble.sample D/BluetoothManager: getConnectedDevices
08-17 07:32:26.368 7477-7498/com.polidea.rxandroidble.sample D/RxBle#Radio: FINISHED RxBleRadioOperationDisconnect(266187038)
08-17 07:32:26.368 7477-7477/com.polidea.rxandroidble.sample D/BluetoothGatt: close()
08-17 07:32:26.368 7477-7477/com.polidea.rxandroidble.sample D/BluetoothGatt: unregisterApp() - mClientIf=5
```
You will see BluetoothGatt do not close when onDestory immediately
#### Preconditions
<br />The device is offline,try to connect it.
#### Steps to reproduce actual result
1.Connect a offline device
2.Exit activity 
#### Actual result
<br />The BluetoothGatt not close right now
#### Expected result
<br />The BluetoothGatt close right now

**Comment by kexuejin** [comment] 2016-08-17 10:21
By the way,if device is try to connect, 
at the same time  to scan device,the scan will return nothing until device gatt close,please help me.

**Comment by dariuszseweryn** [comment] 2016-08-17 10:46
Hello @kexuejin 
I am currently working on the fix to close the connection asap. For the second issue it is by design that only one operation is being performed at the time and establishing the connection is an atomic operation if `autoConnect == false`. Once I will finish the fix scan should happen earlier.
Best Regards

**Comment by kexuejin** [comment] 2016-08-17 14:34
Thank you very much!

**Comment by dariuszseweryn** [comment] 2016-08-18 14:19
Fix is ready. It's waiting for our internal code review but unfortunately it is our holiday season and it may take up to two weeks. If you need it quicker you can always checkout the latest `master` branch and exchange `RxBleRadioOperationConnect.java` file code to:
```
package com.polidea.rxandroidble.internal.operations;

import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothGatt;
import android.support.annotation.NonNull;

import com.polidea.rxandroidble.RxBleConnection;
import com.polidea.rxandroidble.internal.RxBleLog;
import com.polidea.rxandroidble.internal.RxBleRadioOperation;
import com.polidea.rxandroidble.internal.connection.RxBleGattCallback;
import com.polidea.rxandroidble.internal.util.BleConnectionCompat;

import rx.Observable;
import rx.subjects.BehaviorSubject;

import static com.polidea.rxandroidble.RxBleConnection.RxBleConnectionState.CONNECTED;

public class RxBleRadioOperationConnect extends RxBleRadioOperation<BluetoothGatt> {

    private final BluetoothDevice bluetoothDevice;
    private final RxBleGattCallback rxBleGattCallback;
    private final BleConnectionCompat connectionCompat;
    private final boolean autoConnect;
    private BehaviorSubject<BluetoothGatt> bluetoothGattBehaviorSubject = BehaviorSubject.create();
    @SuppressWarnings("Convert2MethodRef")
    private final Runnable releaseRadioRunnable = () -> releaseRadio();
    private final Runnable emptyRunnable = () -> {
    };
    private final BehaviorSubject<Boolean> isSubscribed = BehaviorSubject.create(false);
    private final Observable<BluetoothGatt> asObservable = super.asObservable()
            .doOnSubscribe(() -> isSubscribed.onNext(true))
            .doOnUnsubscribe(() -> isSubscribed.onNext(false))
            .share();

    public RxBleRadioOperationConnect(BluetoothDevice bluetoothDevice, RxBleGattCallback rxBleGattCallback,
                                      BleConnectionCompat connectionCompat, boolean autoConnect) {
        this.bluetoothDevice = bluetoothDevice;
        this.rxBleGattCallback = rxBleGattCallback;
        this.connectionCompat = connectionCompat;
        this.autoConnect = autoConnect;
    }

    @Override
    public Observable<BluetoothGatt> asObservable() {
        return asObservable;
    }

    @Override
    protected void protectedRun() {
        final Runnable onConnectionEstablishedRunnable = autoConnect ? emptyRunnable : releaseRadioRunnable;
        final Runnable onConnectCalledRunnable = autoConnect ? releaseRadioRunnable : emptyRunnable;

        getConnectedBluetoothGatt()
                // when there are no subscribers there is no point of continuing work -> next will be disconnect operation
                .takeUntil(hasNoSubscribers().doOnNext(noSubscribers -> RxBleLog.d("No subscribers, finishing operation")))
                .doOnCompleted(onConnectionEstablishedRunnable::run)
                .subscribe(getSubscriber());
        onConnectCalledRunnable.run();
    }

    @NonNull
    private Observable<Boolean> hasNoSubscribers() {
        return isSubscribed.filter(aBoolean -> !aBoolean);
    }

    /**
     * Emits BluetoothGatt and completes after connection is established.
     *
     * @return BluetoothGatt after connection reaches {@link RxBleConnection.RxBleConnectionState#CONNECTED} state.
     * @throws com.polidea.rxandroidble.exceptions.BleDisconnectedException if connection was disconnected/failed before it was established.
     */
    @NonNull
    private Observable<BluetoothGatt> getConnectedBluetoothGatt() {
        // start connecting the BluetoothGatt
        // note: Due to different Android BLE stack implementations it is not certain whether `connectGatt()` or `BluetoothGattCallback`
        // will emit BluetoothGatt first
        return Observable.fromCallable(() ->
                connectionCompat.connectGatt(bluetoothDevice, autoConnect, rxBleGattCallback.getBluetoothGattCallback())
        )
                .mergeWith(rxBleGattCallback.getBluetoothGatt())
                // relay BluetoothGatt instance updates
                .doOnNext(bluetoothGattBehaviorSubject::onNext)
                // capture BluetoothGatt when connected
                .sample(rxBleGattCallback
                        .getOnConnectionStateChange()
                        .filter(rxBleConnectionState -> rxBleConnectionState == CONNECTED))
                // disconnect may happen even if the connection was not established yet
                .mergeWith(rxBleGattCallback.observeDisconnect())
                .take(1)
                // finish relaying if there won't be more updates
                .doOnTerminate(bluetoothGattBehaviorSubject::onCompleted);
    }

    /**
     * Obtain observable emitting most recent {@link BluetoothGatt instance}.
     * NOTE: Connection may be released and/or GATT may be closed in any point of time.
     *
     * @return Observable with BluetoothGatt. Most recent GATT will be emitted instantly after subscription if it is available.
     */
    public Observable<BluetoothGatt> getBluetoothGatt() {
        return bluetoothGattBehaviorSubject;
    }
}
```

Best Regards

**Comment by s0nerik** [comment] 2016-09-05 15:21
Hey guys, I suddenly found that reverting the RxJava version to 1.1.7 (previously was 1.1.9) seems to help with this problem. I'm gonna assume there were some changes in the way Subjects work in the later versions that made the library behave strangely.

**Comment by kexuejin** [comment] 2016-09-06 01:17
Maybe, but i don't want to reverting to rxjava version...

**Comment by dariuszseweryn** [comment] 2016-09-08 10:16
Fixed with https://github.com/Polidea/RxAndroidBle/commit/604853c4f39c5e8a19e02415c50b547b0befd0e7 
Should be available in the SNAPSHOT shortly.

**Closed by dariuszseweryn** 2016-09-08 10:16 UTC
Labels: bug
